### ISSUE TITLE
Compatibility with 2channel tripcodes

### ISSUE THREAD

**Issue by iccanobif** [KenanY/tripcode#82]
Hello, I just realized that 2channel (now 5channel) and all other japanese websites with tripcode support I could try don't have an htmlEscape() step while calculating the tripcode, so for example ```&``` as a key translates to ◆2r2Ga7GHRc on 5channel while it becomes ◆MhCJJ7GVT. on 4chan.

Is it okay if I make a pull request to add a parameter to choose whether to calculate the tripcode in a 5chan or 4chan compatible mode (for example something like ```tripcode("key", { mode: "2chan" })``` to skip the htmlEscape() call)? I don't mind making my own fork if you'd rather keep this library 4chan compatible only, of course.

**Comment by KenanY** [comment]
Hmm, I think we should just do a fork here. I'd rather keep each package focused on a single type and not go down the rabbit hole of trying to support multiple sites within one package.
